//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 NDD.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Interface) DeepCopyInto(out *Interface) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(InterfaceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Interface.
func (in *Interface) DeepCopy() *Interface {
	if in == nil {
		return nil
	}
	out := new(Interface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceConfig) DeepCopyInto(out *InterfaceConfig) {
	*out = *in
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Lacp != nil {
		in, out := &in.Lacp, &out.Lacp
		*out = new(bool)
		**out = **in
	}
	if in.LacpFallback != nil {
		in, out := &in.LacpFallback, &out.LacpFallback
		*out = new(bool)
		**out = **in
	}
	if in.Lag != nil {
		in, out := &in.Lag, &out.Lag
		*out = new(bool)
		**out = **in
	}
	if in.LagMember != nil {
		in, out := &in.LagMember, &out.LagMember
		*out = new(bool)
		**out = **in
	}
	if in.LagName != nil {
		in, out := &in.LagName, &out.LagName
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceConfig.
func (in *InterfaceConfig) DeepCopy() *InterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(InterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceSpec) DeepCopyInto(out *InterfaceSpec) {
	*out = *in
	if in.Interface != nil {
		in, out := &in.Interface, &out.Interface
		*out = new(Interface)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceSpec.
func (in *InterfaceSpec) DeepCopy() *InterfaceSpec {
	if in == nil {
		return nil
	}
	out := new(InterfaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceStatus) DeepCopyInto(out *InterfaceStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceStatus.
func (in *InterfaceStatus) DeepCopy() *InterfaceStatus {
	if in == nil {
		return nil
	}
	out := new(InterfaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceSubinterface) DeepCopyInto(out *InterfaceSubinterface) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(InterfaceSubinterfaceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(string)
		**out = **in
	}
	if in.Ipv4 != nil {
		in, out := &in.Ipv4, &out.Ipv4
		*out = make([]*InterfaceSubinterfaceIpv4, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(InterfaceSubinterfaceIpv4)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Ipv6 != nil {
		in, out := &in.Ipv6, &out.Ipv6
		*out = make([]*InterfaceSubinterfaceIpv6, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(InterfaceSubinterfaceIpv6)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceSubinterface.
func (in *InterfaceSubinterface) DeepCopy() *InterfaceSubinterface {
	if in == nil {
		return nil
	}
	out := new(InterfaceSubinterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceSubinterfaceConfig) DeepCopyInto(out *InterfaceSubinterfaceConfig) {
	*out = *in
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(uint32)
		**out = **in
	}
	if in.InnerVlanId != nil {
		in, out := &in.InnerVlanId, &out.InnerVlanId
		*out = new(uint16)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.OuterVlanId != nil {
		in, out := &in.OuterVlanId, &out.OuterVlanId
		*out = new(uint16)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceSubinterfaceConfig.
func (in *InterfaceSubinterfaceConfig) DeepCopy() *InterfaceSubinterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(InterfaceSubinterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceSubinterfaceIpv4) DeepCopyInto(out *InterfaceSubinterfaceIpv4) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(InterfaceSubinterfaceIpv4Config)
		(*in).DeepCopyInto(*out)
	}
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceSubinterfaceIpv4.
func (in *InterfaceSubinterfaceIpv4) DeepCopy() *InterfaceSubinterfaceIpv4 {
	if in == nil {
		return nil
	}
	out := new(InterfaceSubinterfaceIpv4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceSubinterfaceIpv4Config) DeepCopyInto(out *InterfaceSubinterfaceIpv4Config) {
	*out = *in
	if in.IpAddress != nil {
		in, out := &in.IpAddress, &out.IpAddress
		*out = new(string)
		**out = **in
	}
	if in.IpCidr != nil {
		in, out := &in.IpCidr, &out.IpCidr
		*out = new(string)
		**out = **in
	}
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = new(string)
		**out = **in
	}
	if in.PrefixLength != nil {
		in, out := &in.PrefixLength, &out.PrefixLength
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceSubinterfaceIpv4Config.
func (in *InterfaceSubinterfaceIpv4Config) DeepCopy() *InterfaceSubinterfaceIpv4Config {
	if in == nil {
		return nil
	}
	out := new(InterfaceSubinterfaceIpv4Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceSubinterfaceIpv6) DeepCopyInto(out *InterfaceSubinterfaceIpv6) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(InterfaceSubinterfaceIpv6Config)
		(*in).DeepCopyInto(*out)
	}
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceSubinterfaceIpv6.
func (in *InterfaceSubinterfaceIpv6) DeepCopy() *InterfaceSubinterfaceIpv6 {
	if in == nil {
		return nil
	}
	out := new(InterfaceSubinterfaceIpv6)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceSubinterfaceIpv6Config) DeepCopyInto(out *InterfaceSubinterfaceIpv6Config) {
	*out = *in
	if in.IpAddress != nil {
		in, out := &in.IpAddress, &out.IpAddress
		*out = new(string)
		**out = **in
	}
	if in.IpCidr != nil {
		in, out := &in.IpCidr, &out.IpCidr
		*out = new(string)
		**out = **in
	}
	if in.IpPrefix != nil {
		in, out := &in.IpPrefix, &out.IpPrefix
		*out = new(string)
		**out = **in
	}
	if in.PrefixLength != nil {
		in, out := &in.PrefixLength, &out.PrefixLength
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceSubinterfaceIpv6Config.
func (in *InterfaceSubinterfaceIpv6Config) DeepCopy() *InterfaceSubinterfaceIpv6Config {
	if in == nil {
		return nil
	}
	out := new(InterfaceSubinterfaceIpv6Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceSubinterfaceSpec) DeepCopyInto(out *InterfaceSubinterfaceSpec) {
	*out = *in
	if in.InterfaceName != nil {
		in, out := &in.InterfaceName, &out.InterfaceName
		*out = new(string)
		**out = **in
	}
	if in.InterfaceSubinterface != nil {
		in, out := &in.InterfaceSubinterface, &out.InterfaceSubinterface
		*out = new(InterfaceSubinterface)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceSubinterfaceSpec.
func (in *InterfaceSubinterfaceSpec) DeepCopy() *InterfaceSubinterfaceSpec {
	if in == nil {
		return nil
	}
	out := new(InterfaceSubinterfaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterfaceSubinterfaceStatus) DeepCopyInto(out *InterfaceSubinterfaceStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterfaceSubinterfaceStatus.
func (in *InterfaceSubinterfaceStatus) DeepCopy() *InterfaceSubinterfaceStatus {
	if in == nil {
		return nil
	}
	out := new(InterfaceSubinterfaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddaInterface) DeepCopyInto(out *NddaInterface) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddaInterface.
func (in *NddaInterface) DeepCopy() *NddaInterface {
	if in == nil {
		return nil
	}
	out := new(NddaInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NddaInterface) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddaInterfaceList) DeepCopyInto(out *NddaInterfaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NddaInterface, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddaInterfaceList.
func (in *NddaInterfaceList) DeepCopy() *NddaInterfaceList {
	if in == nil {
		return nil
	}
	out := new(NddaInterfaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NddaInterfaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddaInterfaceSubinterface) DeepCopyInto(out *NddaInterfaceSubinterface) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddaInterfaceSubinterface.
func (in *NddaInterfaceSubinterface) DeepCopy() *NddaInterfaceSubinterface {
	if in == nil {
		return nil
	}
	out := new(NddaInterfaceSubinterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NddaInterfaceSubinterface) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddaInterfaceSubinterfaceList) DeepCopyInto(out *NddaInterfaceSubinterfaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NddaInterfaceSubinterface, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddaInterfaceSubinterfaceList.
func (in *NddaInterfaceSubinterfaceList) DeepCopy() *NddaInterfaceSubinterfaceList {
	if in == nil {
		return nil
	}
	out := new(NddaInterfaceSubinterfaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NddaInterfaceSubinterfaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddaNetworkInstance) DeepCopyInto(out *NddaNetworkInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddaNetworkInstance.
func (in *NddaNetworkInstance) DeepCopy() *NddaNetworkInstance {
	if in == nil {
		return nil
	}
	out := new(NddaNetworkInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NddaNetworkInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddaNetworkInstanceList) DeepCopyInto(out *NddaNetworkInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NddaNetworkInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddaNetworkInstanceList.
func (in *NddaNetworkInstanceList) DeepCopy() *NddaNetworkInstanceList {
	if in == nil {
		return nil
	}
	out := new(NddaNetworkInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NddaNetworkInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddaSystemPlatform) DeepCopyInto(out *NddaSystemPlatform) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddaSystemPlatform.
func (in *NddaSystemPlatform) DeepCopy() *NddaSystemPlatform {
	if in == nil {
		return nil
	}
	out := new(NddaSystemPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NddaSystemPlatform) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NddaSystemPlatformList) DeepCopyInto(out *NddaSystemPlatformList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NddaSystemPlatform, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NddaSystemPlatformList.
func (in *NddaSystemPlatformList) DeepCopy() *NddaSystemPlatformList {
	if in == nil {
		return nil
	}
	out := new(NddaSystemPlatformList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NddaSystemPlatformList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInstance) DeepCopyInto(out *NetworkInstance) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(NetworkInstanceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInstance.
func (in *NetworkInstance) DeepCopy() *NetworkInstance {
	if in == nil {
		return nil
	}
	out := new(NetworkInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInstanceConfig) DeepCopyInto(out *NetworkInstanceConfig) {
	*out = *in
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(uint32)
		**out = **in
	}
	if in.Interface != nil {
		in, out := &in.Interface, &out.Interface
		*out = make([]*NetworkInstanceConfigInterface, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(NetworkInstanceConfigInterface)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RouterId != nil {
		in, out := &in.RouterId, &out.RouterId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInstanceConfig.
func (in *NetworkInstanceConfig) DeepCopy() *NetworkInstanceConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkInstanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInstanceConfigInterface) DeepCopyInto(out *NetworkInstanceConfigInterface) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInstanceConfigInterface.
func (in *NetworkInstanceConfigInterface) DeepCopy() *NetworkInstanceConfigInterface {
	if in == nil {
		return nil
	}
	out := new(NetworkInstanceConfigInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInstanceSpec) DeepCopyInto(out *NetworkInstanceSpec) {
	*out = *in
	if in.NetworkInstance != nil {
		in, out := &in.NetworkInstance, &out.NetworkInstance
		*out = new(NetworkInstance)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInstanceSpec.
func (in *NetworkInstanceSpec) DeepCopy() *NetworkInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInstanceStatus) DeepCopyInto(out *NetworkInstanceStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInstanceStatus.
func (in *NetworkInstanceStatus) DeepCopy() *NetworkInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemPlatform) DeepCopyInto(out *SystemPlatform) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(SystemPlatformConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemPlatform.
func (in *SystemPlatform) DeepCopy() *SystemPlatform {
	if in == nil {
		return nil
	}
	out := new(SystemPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemPlatformConfig) DeepCopyInto(out *SystemPlatformConfig) {
	*out = *in
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(uint32)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemPlatformConfig.
func (in *SystemPlatformConfig) DeepCopy() *SystemPlatformConfig {
	if in == nil {
		return nil
	}
	out := new(SystemPlatformConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemPlatformSpec) DeepCopyInto(out *SystemPlatformSpec) {
	*out = *in
	if in.SystemPlatform != nil {
		in, out := &in.SystemPlatform, &out.SystemPlatform
		*out = new(SystemPlatform)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemPlatformSpec.
func (in *SystemPlatformSpec) DeepCopy() *SystemPlatformSpec {
	if in == nil {
		return nil
	}
	out := new(SystemPlatformSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemPlatformStatus) DeepCopyInto(out *SystemPlatformStatus) {
	*out = *in
	in.ConditionedStatus.DeepCopyInto(&out.ConditionedStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemPlatformStatus.
func (in *SystemPlatformStatus) DeepCopy() *SystemPlatformStatus {
	if in == nil {
		return nil
	}
	out := new(SystemPlatformStatus)
	in.DeepCopyInto(out)
	return out
}
